# Generated by Django 3.2.11 on 2022-01-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0002_auto_20220128_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemmoryBoxSession',
            new_name='MemoryBoxSession',
        ),
    ]
