# Generated by Django 3.2.11 on 2022-02-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0003_rename_memmoryboxsession_memoryboxsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('slideshow_id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_id', models.CharField(max_length=255)),
                ('media_url', models.CharField(max_length=2048)),
                ('tick_count', models.IntegerField()),
                ('ping_datetime', models.DateTimeField()),
            ],
        ),
    ]
