# Generated by Django 3.2.11 on 2022-02-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0004_slideshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='knowledge_base_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='memoryboxsession',
            name='carepartner_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memoryboxsession',
            name='researcher_flag',
            field=models.BooleanField(default=False),
        ),
    ]
