# Generated by Django 3.2.11 on 2022-02-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0006_auto_20220215_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryboxsessionmedia',
            old_name='meida_end_datetime',
            new_name='media_end_datetime',
        ),
    ]
