# Generated by Django 3.2.11 on 2022-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0007_rename_meida_end_datetime_memoryboxsessionmedia_media_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryboxsessionmedia',
            name='resident_motion',
            field=models.JSONField(max_length=2048, null=True),
        ),
    ]
