# Generated by Django 3.2.11 on 2022-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0008_auto_20220219_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainteraction',
            name='elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
