# Generated by Django 3.2.11 on 2022-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0009_mediainteraction_elapsed_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryboxsessionmedia',
            name='media_analysis',
            field=models.JSONField(max_length=2048, null=True),
        ),
    ]
