# Generated by Django 3.2.11 on 2022-02-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0010_memoryboxsessionmedia_media_analysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryboxsessionmedia',
            old_name='media_analysis',
            new_name='audio_features',
        ),
    ]
