# Generated by Django 3.2.11 on 2022-02-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0011_rename_media_analysis_memoryboxsessionmedia_audio_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryboxsessionmedia',
            old_name='audio_features',
            new_name='media_features',
        ),
    ]
