# Generated by Django 3.2.11 on 2022-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0012_rename_audio_features_memoryboxsessionmedia_media_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediainteraction',
            options={'ordering': ['log_datetime']},
        ),
        migrations.AlterModelOptions(
            name='memoryboxsession',
            options={'ordering': ['-session_start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='memoryboxsessionmedia',
            options={'ordering': ['media_start_datetime']},
        ),
        migrations.AddField(
            model_name='mediainteraction',
            name='analysis',
            field=models.JSONField(max_length=2048, null=True),
        ),
    ]
