# Generated by Django 3.2.11 on 2022-02-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joi', '0013_auto_20220223_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMessage',
            fields=[
                ('device_message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_datetime', models.DateTimeField()),
                ('message', models.JSONField(max_length=2048)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='joi.device')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='joi.resident')),
            ],
        ),
    ]
